name: CI
on: push

jobs: 
  run:
    name: Update documentation
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install dependencies
      run: npm install
    
    - name: Compile code
    - run: npm run compile
    - run: npm run docs

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Pavel Surinin
        author_email: pavel.surinin@gmail.com
        message: "updating docs"
        add: "*.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
